name: E2E

on: [workflow_dispatch, push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Use Node.js v21.0.0
        uses: actions/setup-node@v3
        with:
          node-version: '21.0.0'
      
      - name: Install node dependeces
        run: npm install

      - name: Run tests
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 10 
          max_attempts: 2
          retry_on: error
          command: npm test